--- 
javascripts: 
- base: 
  - jquery-1.3.2.min
  - jmodal
  - jquery.validate.min
  - jquery.tooltip.min
  - swfobject
  - stars/jquery-ui-1.7.2.custom
  - stars/ui.core
  - stars/ui.stars
  - application
stylesheets: 
- base: 
  - ui.stars
  - application
  - jmodal
